
export const GET_COMPANY_LOADING = 'GET_COMPANY_LOADING';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';

export const GET_COMPANY_ERROR = 'GET_COMPANY_ERROR';

export const GET_STAFF_LOADING = 'GET_STAFF_LOADING'
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS'
export const GET_STAFF_ERROR = 'GET_STAFF_ERROR'

export const ADD_CART_LOADING = 'ADD_CART_LOADING'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'
export const ADD_CART_ERROR = 'ADD_CART_ERROR'

export const DELETE_CART_LOADING = 'DELETE_CART_LOADING'
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS'
export const DELETE_CART_ERROR = 'DELETE_CART_ERROR'

export const GET_ORDERS_LOADING = 'GET_ORDERS_LOADING'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_PAST_ORDERS_SUCCESS = 'GET_PAST_ORDERS_SUCCESS'
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR'

export const ADD_ORDER_LOADING = 'ADD_ORDER_LOADING'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_ERROR = 'ADD_ORDER_ERROR'

export const DELETE_ORDER_LOADING = 'DELETE_ORDER_LOADING'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_ERROR = 'DELETE_ORDER_ERROR'

export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const SIGNUP_USER_LOADING = 'SIGNUP_USER_LOADING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const FORGOT_USER_SUCCESS = 'FORGOT_USER_SUCCESS';
export const FORGOT_USER_ERROR = 'FORGOT_USER_ERROR'

export const RESET_USER_SUCCESS = 'RESET_USER_SUCCESS';
export const RESET_USER_LOADING = 'RESET_USER_LOADING';
export const RESET_USER_ERROR = 'RESET_USER_ERROR';

export const GET_USER_LOADING = 'GET_USER_LOADING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export interface e {
  key: string
}

