
export const GET_COMPANY_LOADING = 'GET_COMPANY_LOADING';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';

export const GET_COMPANY_ERROR = 'GET_COMPANY_ERROR';

export const GET_STAFF_LOADING = 'GET_STAFF_LOADING'
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS'
export const GET_STAFF_ERROR = 'GET_STAFF_ERROR'

export const ADD_STAFF_LOADING = 'ADD_STAFF_LOADING'
export const ADD_STAFF_SUCCESS = 'ADD_STAFF_SUCCESS'
export const ADD_STAFF_ERROR = 'ADD_STAFF_ERROR'



export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';



export interface e {
  key: string
}

